### ISSUE TITLE
Main window application size

### ISSUE THREAD

**Issue by Froststorm** [DmitriyBalykin/HomeCalc#10]
Expected behavior :
Application window should maintain persistent size .
Actual behavior :
Aplication changes size of window while clicking on tabs
Steps to reproduce:
Click from first tab to last, observing size of window

**Comment by DmitriyBalykin** [comment]
Please provide issue info in next format:
- Expected behavior (e.g. "window size should be fixed and equal 1000x300px" )
- Actual behavior (what we got now)
- Steps to reproduce (in a not obvious case)

**Comment by DmitriyBalykin** [comment]
What size is preferable?

**Comment by Froststorm** [comment]
Any size window in which all data will be readable.
