### ISSUE TITLE
Can not change value in fields while pressed "Считать"

### ISSUE THREAD

**Issue by Froststorm** [DmitriyBalykin/HomeCalc#13]
- Expected behavior 
  While preesed button(?) "Считать" i can change values
- Actual behavior (what we got now)
  While preesed button(?) "Считать" i can not change values
- Steps to reproduce (in a not obvious case)
  Choose  "Тип покупки", fill "Название покупки", fill fields "Количество" and "Цена за единицу", press "Считать" try to change field above pressed button

**Comment by DmitriyBalykin** [comment]
Because button "Считать" sets value which should be calculated, this value completely depends on two other value. So this behavior is by design.
